spring:
  datasource:
    url: jdbc:sqlserver://localhost;instanceName=BOOKSQL;databaseName=BookTracker;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong(!)Password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080